In [1]:
#Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.24.4


In [2]:
#How to create a 1D array?
import numpy as np
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [4]:
#How to create a boolean array?
import numpy as np
boolean_array = np.ones((3,3), dtype="int32")
print(boolean_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
#How to extract items that satisfy a given condition from 1D array?
#Extract all odd numbers from arr
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[arr%2==1]
print(result)

[1 3 5 7 9]


In [23]:
#How to replace items that satisfy a condition with another value in numpy array?
#Replace all odd numbers in arr with -1
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
